### PR TITLE
Added similar cards example list

### LINKED ISSUE #916: Show a list of "Similar cards" when adding a card
Sometimes a user may forget or be unaware that they already created duplicate card in the past.
Searching manually and tedious and prone to typos and errors.

It would be nice to have a list of "similar cards" right below "Front side" and "Back side" inputs, built in real time as the user starts typing.

The match on card contents could be fuzzy (i.e.: "frst" matches "first").

Mockup:
similar_cards

### PR DESCRIPTION
**Pull request by jddeep**
Added similar cards example list.
 
Fixes #916

### CODE REVIEW

**Comment by jddeep** [comment]
@ksheremet Please review.

**Comment by jddeep** [comment]
WIP

**Comment by jddeep** [comment]
@ksheremet Please review this.

**Comment by ksheremet** [comment]
@jddeep What happens when user starts to type a new card? Does it update a list of similar cards?
Please add screenshots to show that it works.

**Comment by jddeep** [comment]
No @ksheremet Actually right now. It shows only a progress bar.

**Comment by ksheremet** [comment]
@jddeep Why do you ask to review the code that doesn't work?

**Comment by jddeep** [comment]
@ksheremet I ask for a initial review to get a confirmation on my approach towards the issue.

**Comment by jddeep** [comment]
And moreover you have a better know how of the codebase, so like if there are small parts which i can be missing you can give me a idea on that. I know you want a PR on the issue fully fixed. But it is just an approach i follow. I will make sure from next PR. Thanks.

**Comment by jddeep** [comment]
@ksheremet @dotdoom I have tried wrapping the `ObservableGridWidget` with `Flex` as well but get the same error as this:
```I/flutter (21844): The following assertion was thrown during performLayout():
I/flutter (21844): RenderFlex children have non-zero flex but incoming height constraints are unbounded.```

**Comment by jddeep** [comment]
@ksheremet @dotdoom The problem is that only the card grid list is not getting rendered on the screen.

**Comment by jddeep** [comment]
@ksheremet @dotdoom Should I try placing the grid widget in an `Expanded` ?

**Comment by jddeep** [comment]
@ksheremet @dotdoom After wrapping with Expanded, I get the error `Incorrect use of ParentDataWidget`

**Pull request closed without merging**
