### PR TITLE
Added emptylistmsgwidget_test

### LINKED ISSUE #934: Tests: Create widget test for empty_list_message_widget.dart
Create widget test for https://github.com/dasfoo/delern/blob/master/flutter/lib/views/helpers/empty_list_message_widget.dart

Widget test doc: https://flutter.dev/docs/cookbook/testing/widget/introduction

### PR DESCRIPTION
**Pull request by jddeep**
Added emptylistmsgwidget_test. Fix #934 .

### CODE REVIEW

**Comment by jddeep** [comment]
@ksheremet @dotdoom please review.

**Comment by jddeep** [comment]
And @ksheremet @dotdoom please send me over the googleservices.json file as otherwise I have build fails on my machine locally.

**Comment by jddeep** [comment]
@ksheremet @dotdoom can you please tell why in particular is the ci build is failing?

**Comment by ksheremet** [comment]
Hi @jddeep,

Thanks for your PR!
Build failed because your test is failing. When I run your test it throws the following exception:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Text("Message Widget Test...", inherit: true, color:
Color(0xdd000000), size: 16.0, weight: 400):
No Directionality widget found.
RichText widgets require a Directionality widget ancestor.
The specific widget that could not find a Directionality ancestor was:
  RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Message Widget Test...")
The ownership chain for the affected widget is:
  RichText ← Text ← Center ← EmptyListMessageWidget ← [root]
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
top of your application widget tree. It determines the ambient reading direction and is used, for
example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
``` 

Could you please fix the test that it works? The correctness you can check in your IDE when you run the test.

Your code causes a lot of files movements that are not related to this PR. Could you please remove these changes from your PR? It would be ideally to have only changes that are related to the issue. (file with the test)

Here is [link](https://github.com/dasfoo/delern/wiki/Working-with-GitHub) that explains how to do PR in Delern. Could you please do PR to `gssoc19` branch?

It can be useful as well:
- [Code formatting](https://flutter.dev/docs/development/tools/formatting) 
- [Delern Wiki](https://github.com/dasfoo/delern/wiki)  :)

**Comment by jddeep** [comment]
@ksheremet then shall i make a same pr in the gssoc19 branch? Or should I first close it here?

**Comment by ksheremet** [comment]
@jddeep Please close it here and make a new one to the 
gssoc19 branch

**Pull request closed without merging**
