### PR TITLE
add screenshots of new design in screenshots/New design directory

### LINKED ISSUE #971: UX: Suggest colors for App(primary, accent, secondary, etc)
Create a new design for the app with colors that provides good accessibility. Consider good contrast
For example:
Now:
Screenshot_20190314-121828

Background color and foreground color have not a good contrast. Therefore accessibility scanner shows warnings. 
Example of fixing it by changing primary color:
Screenshot_20190314-115823

__TODO:__
1. Use (Material Design)[https://material.io/]
1. Consider to keep all colors and styles in https://github.com/dasfoo/delern/blob/master/flutter/lib/flutter/styles.dart
1. Move hardcoded colors from [main.dart](https://github.com/dasfoo/delern/blob/master/flutter/lib/main.dart#L44) in file provided above (styles.dart)
1. Suggest new colors for text, foreground, etc
1. Do not forget to add a screenshot with your PR

__Useful links:__
- https://flutter.dev/docs/development/accessibility-and-localization/accessibility
- Accessibility Scanner - https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en
- https://medium.com/flutter-community/a-deep-dive-into-flutters-accessibility-widgets-eb0ef9455bc
- https://codelabs.developers.google.com/codelabs/mdc-103-flutter/index.html?index=..%2F..index#0

### PR DESCRIPTION
**Pull request by vsharma20v**
add screenshots of new design in screenshots/New design directory.
Issue Fixed #971 
Design Link: https://www.figma.com/file/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?node-id=27%3A2
Prototype Link: https://www.figma.com/proto/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?scaling=scale-down

### CODE REVIEW

**Comment by ksheremet** [comment]
@vsharma20v 
It looks good to me. 
Could you please do PR to gssoc19 branch?
https://github.com/dasfoo/delern/wiki/Working-with-GitHub

**Comment by vsharma20v** [comment]
> @vsharma20v
> It looks good to me.
> Could you please do PR to gssoc19 branch?
> https://github.com/dasfoo/delern/wiki/Working-with-GitHub

Ok I will do that

**Comment by ksheremet** [comment]
@vsharma20v 
Please do not move old screenshots as well. They are used in Readme.

**Comment by vsharma20v** [comment]
> @vsharma20v
> Please do not move old screenshots as well. They are used in Readme.

Is my way of putting them in a folder name 'Old design' in screenshots folder is good?

**Comment by ksheremet** [comment]
@vsharma20v
no, just leave them as they are.

**Comment by vsharma20v** [comment]
> @vsharma20v
> no, just leave them as they are.

ok

**Comment by vsharma20v** [comment]
Can I close this PR and open another?

**Comment by ksheremet** [comment]
yes

**Pull request closed without merging**
